// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwOYovroUs-Ook7vX6SGsf6H1op70HGzo',
    appId: '1:452558000976:web:c02132587831a730939255',
    messagingSenderId: '452558000976',
    projectId: 'aluinternlink',
    authDomain: 'aluinternlink.firebaseapp.com',
    storageBucket: 'aluinternlink.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fL453rVILNj0mgkhKXtCbD0lTSJzOi4',
    appId: '1:452558000976:android:688f65065080ed53939255',
    messagingSenderId: '452558000976',
    projectId: 'aluinternlink',
    storageBucket: 'aluinternlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyhPXxw0zwFJ7o3EDaC4vcwgE1Cy7Rs8',
    appId: '1:452558000976:ios:f4cfa4139d919e1f939255',
    messagingSenderId: '452558000976',
    projectId: 'aluinternlink',
    storageBucket: 'aluinternlink.firebasestorage.app',
    iosBundleId: 'com.example.aluInternlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyhPXxw0zwFJ7o3EDaC4vcwgE1Cy7Rs8',
    appId: '1:452558000976:ios:f4cfa4139d919e1f939255',
    messagingSenderId: '452558000976',
    projectId: 'aluinternlink',
    storageBucket: 'aluinternlink.firebasestorage.app',
    iosBundleId: 'com.example.aluInternlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwOYovroUs-Ook7vX6SGsf6H1op70HGzo',
    appId: '1:452558000976:web:d6eea10560295021939255',
    messagingSenderId: '452558000976',
    projectId: 'aluinternlink',
    authDomain: 'aluinternlink.firebaseapp.com',
    storageBucket: 'aluinternlink.firebasestorage.app',
  );
}
